src/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.IndexView.as_view()),
    path('add/', views.AddView.as_view(), name='add'),
    path('posts/', views.PostsView.as_view(), name='posts'),
    path('<slug:slug>/', views.SingleView.as_view(), name='single'),
    path('edit/<int:pk>/', views.EditView.as_view(), name='edit'),
    path('delete/<int:pk>/', views.Delete.as_view(), name='delete'),
]

src/firststepcms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
]

src/core/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User


class Core(models.Model):

    title = models.CharField(max_length=200)
    excerpt = models.TextField(null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='core')
    slug = models.SlugField(max_length=100, unique=True)
    published = models.DateTimeField(default=timezone.now)

    def get_absolute_url(self):
        return reverse('core:single', args=[self.slug])

    class Meta:
        ordering = ['-published']

    def __str__(self):
        return self.title

src/core/forms.py
from django import forms
from .models import Core


class PostForm(forms.ModelForm):
    class Meta:
        model = Core
        fields = "__all__"

src/core/views.py
from .models import Core
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, CreateView
from django.urls import reverse_lazy


class IndexView(ListView):
    model = Core
    template_name = 'core/index.html'
    context_object_name = 'index'


class SingleView(DetailView):
    model = Core
    template_name = 'core/single.html'
    context_object_name = 'post'


class PostsView(ListView):
    model = Core
    template_name = 'core/posts.html'
    context_object_name = 'post_list'


class AddView(CreateView):
    model = Core
    template_name = 'core/add.html'
    fields = '__all__'
    success_url = reverse_lazy('core:posts')


class EditView(UpdateView):
    model = Core
    template_name = 'core/edit.html'
    fields = '__all__'
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('core:posts')


class Delete(DeleteView):
    model = Core
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('core:posts')
    template_name = 'core/confirm-delete.html'

src/templates/core/add.html
{% extends 'core/base.html' %} {% load widget_tweaks %} {% block content %}

<div class="container pt-5">
  <form method="post" novalidate>
    {% csrf_token %} {% for field in form.visible_fields %}
    <div class="form-group">
      <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {{ field|add_class:'form-control' }} {% for error in field.errors %}
      <span class="help-block">{{ error }}</span>
      {% endfor %}
    </div>
    {% endfor %}
    <div class="form-group">
      <button type="submit" class="btn btn-success">
        <span class="glyphicon glyphicon-ok"></span> Edit
      </button>
      <a href="{% url 'core:posts' %}" class="btn btn-default">Cancel</a>
    </div>
  </form>
</div>

{% endblock %}

src/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />

    <title>CMS Primer</title>
  </head>
  <body>
    {% include 'core/navbar.html' %} {% block content %} {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>

    {% include 'core/footer.html' %}
  </body>
</html>

src/templates/core/confirm-delete.html
{% extends 'core/base.html' %} {% block content %}

<div class="container pt-5">
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
  </form>
</div>

{% endblock %}

src/templates/core/edit.html
{% extends 'core/base.html' %} {% load widget_tweaks %} {% block content %}

<div class="container pt-5">
  <form method="post" novalidate>
    {% csrf_token %} {% for field in form.visible_fields %}
    <div class="form-group">
      <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {{ field|add_class:'form-control' }} {% for error in field.errors %}
      <span class="help-block">{{ error }}</span>
      {% endfor %}
    </div>
    {% endfor %}
    <div class="form-group">
      <button type="submit" class="btn btn-success">
        <span class="glyphicon glyphicon-ok"></span> Edit
      </button>
      <a href="{% url 'core:posts' %}" class="btn btn-default">Cancel</a>
    </div>
  </form>
</div>

{% endblock %}

src/templates/core/footer.html
<div class="container">
  <footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        CMS Primer
        <small class="d-block mb-3 text-muted"
          >Another veryacademy example</small
        >
      </div>
      <div class="col-6 col-md">
        <h5>Admin</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Post Admin</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>About Us</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Home</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Resources</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Sample Code Resource</a></li>
          <li><a class="text-muted" href="#">YouTube Link</a></li>
        </ul>
      </div>
    </div>
  </footer>
</div>

src/templates/core/index.html
{% extends 'core/base.html' %} {% block content %}

<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      {% for core in object_list %}
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <img
            class="card-img-top"
            src="https://via.placeholder.com/150x100"
            alt="Card image cap"
          />
          <div class="card-body">
            <h4 class="">
              <a href="{{ core.get_absolute_url }}">{{ core.title }}</a>
            </h4>
            <p class="card-text"></p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="">
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

{% endblock %}

src/templates/core/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a href="#" class="navbar-brand d-flex align-items-center">
    <svg
      class="bi bi-display-fill mr-2"
      width="1em"
      height="1em"
      viewBox="0 0 16 16"
      fill="currentColor"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M5.75 13.5c.167-.333.25-.833.25-1.5h4c0 .667.083 1.167.25 1.5H11a.5.5 0 010 1H5a.5.5 0 010-1h.75z"
      />
      <path
        fill-rule="evenodd"
        d="M13.991 3H2c-.325 0-.502.078-.602.145a.758.758 0 00-.254.302A1.46 1.46 0 001 4.01V10c0 .325.078.502.145.602.07.105.17.188.302.254a1.464 1.464 0 00.538.143L2.01 11H14c.325 0 .502-.078.602-.145a.758.758 0 00.254-.302 1.464 1.464 0 00.143-.538L15 9.99V4c0-.325-.078-.502-.145-.602a.757.757 0 00-.302-.254A1.46 1.46 0 0013.99 3zM14 2H2C0 2 0 4 0 4v6c0 2 2 2 2 2h12c2 0 2-2 2-2V4c0-2-2-2-2-2z"
        clip-rule="evenodd"
      />
      <path d="M2 4h12v6H2z" />
    </svg>
    <strong>CMS Primer</strong>
  </a>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'core:posts' %}">Manage Posts</a>
      </li>
    </ul>
  </div>
</nav>

src/templates/core/post-detail.html
{% extends 'core/base.html' %} {% block content %}
<div class="container-fluid">
  <div class="row"></div>
  <br />
  <div class="row">
    <div class="col-md-1 col-xs-1 col-sm-1"></div>
    <div class="col-md-8 col-xs-8 col-sm-8">
      <p class="h2">{{post.title}}</p>
    </div>
    <div class="col-md-1 col-xs-1 col-sm-1">
      <a href="{% url 'edit' post.pk %}">
        <button type="button" class="btn btn-info">
          <span class="glyphicon glyphicon-pencil"></span>
        </button>
      </a>
    </div>
    <div class="col-md-1 col-xs-1 col-sm-1">
      <a href="{% url 'delete' post.pk %}">
        <button type="button" class="btn btn-danger">
          <span class="glyphicon glyphicon-trash"></span>
        </button>
      </a>
    </div>
    <div class="col-md-1 col-xs-1 col-sm-1"></div>
  </div>
  <div class="row">
    <div class="col-md-1 col-xs-1 col-sm-1"></div>
    <div class="col-md-10 col-xs-10 col-sm-10">{{post.message}}</div>
    <div class="col-md-1 col-xs-1 col-sm-1"></div>
  </div>
</div>
{% endblock %}

src/templates/core/posts.html
{% extends 'core/base.html' %} {% block content %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="navbar-brand">Post Administration</div>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'core:add' %}">Add New</a>
      </li>
    </ul>
  </div>
</nav>

<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      {% for post in post_list %}
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <img
            class="card-img-top"
            src="https://via.placeholder.com/150x100"
            alt="Card image cap"
          />
          <div class="card-body">
            <h4 class="lead">
              <a class="text-dark" href="{% url 'core:single' post.pk %}"
                >{{ post.title }}</a
              >
            </h4>
            <p class="card-text"></p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a
                  href="{{ post.get_absolute_url }}"
                  class="btn btn-sm btn-outline-primary"
                  role="button"
                  aria-pressed="true"
                  >View</a
                >
                <a
                  href="{% url 'core:edit' post.pk %}"
                  class="btn btn-sm btn-outline-secondary"
                  role="button"
                  aria-pressed="true"
                  >Edit</a
                >
                <a
                  href="{% url 'core:delete' post.pk %}"
                  class="btn btn-sm btn-outline-secondary"
                  role="button"
                  aria-pressed="true"
                  >Delete</a
                >
              </div>
              <small class="text-muted">9 mins</small>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

{% endblock %}

src/templates/core/single.html
{% extends 'core/base.html' %} {% block content %}
<div class="container">
  <div class="row">
    <div class="col-12 pt-5">
      <img
        class="card-img-top"
        src="https://via.placeholder.com/300x100"
        alt="Card image cap"
      />
      <h2 class="pt-5">{{post.title}}</h2>
      <p>{{post.excerpt}}</p>
    </div>
  </div>
</div>
{% endblock %}